import express from 'express';
import Problem from '../models/Problem.js';

const router = express.Router();

// One-time seed route — protected by a secret key
// Call: GET /api/seed?key=SEED_SECRET
router.get('/', async (req, res) => {
    const { key } = req.query;

    if (key !== process.env.SEED_SECRET) {
        return res.status(403).json({ error: 'Forbidden. Invalid seed key.' });
    }

    const problems = [
        // 1️⃣ PREFIX SUM (8 problems)
        { title: "Running Sum of 1d Array", category: "Prefix Sum", difficulty: "Easy", description: "Given an array nums, return the running sum of nums where runningSum[i] = sum(nums[0]…nums[i]).", testCases: [{ input: "[1,2,3,4]", output: "[1,3,6,10]", isHidden: false }], starterCode: "function runningSum(nums) {\n    // Write your code here\n}" },
        { title: "Find Pivot Index", category: "Prefix Sum", difficulty: "Easy", description: "Find the pivot index where the sum of all numbers to the left equals the sum of all numbers to the right.", testCases: [{ input: "[1,7,3,6,5,6]", output: "3", isHidden: false }], starterCode: "function pivotIndex(nums) {\n    // Write your code here\n}" },
        { title: "Range Sum Query – Immutable", category: "Prefix Sum", difficulty: "Easy", description: "Calculate the sum of elements between indices left and right (inclusive).", testCases: [{ input: "[-2,0,3,-5,2,-1]\\n0\\n2", output: "1", isHidden: false }], starterCode: "class NumArray {\n    constructor(nums) {\n        // Initialize\n    }\n    sumRange(left, right) {\n        // Return sum\n    }\n}" },
        { title: "Subarray Sum Equals K", category: "Prefix Sum", difficulty: "Medium", description: "Find the total number of continuous subarrays whose sum equals to k.", testCases: [{ input: "[1,1,1]\\n2", output: "2", isHidden: false }], starterCode: "function subarraySum(nums, k) {\n    // Write your code here\n}" },
        { title: "Contiguous Array", category: "Prefix Sum", difficulty: "Medium", description: "Find the maximum length of a contiguous subarray with an equal number of 0 and 1.", testCases: [{ input: "[0,1]", output: "2", isHidden: false }], starterCode: "function findMaxLength(nums) {\n    // Write your code here\n}" },
        { title: "Continuous Subarray Sum", category: "Prefix Sum", difficulty: "Medium", description: "Check if the array has a continuous subarray of size at least 2 whose sum is a multiple of k.", testCases: [{ input: "[23,2,4,6,7]\\n6", output: "true", isHidden: false }], starterCode: "function checkSubarraySum(nums, k) {\n    // Write your code here\n}" },
        { title: "Subarray Sums Divisible by K", category: "Prefix Sum", difficulty: "Medium", description: "Return the number of non-empty subarrays that have a sum divisible by k.", testCases: [{ input: "[4,5,0,-2,-3,1]\\n5", output: "7", isHidden: false }], starterCode: "function subarraysDivByK(nums, k) {\n    // Write your code here\n}" },
        { title: "Number of Submatrices That Sum to Target", category: "Prefix Sum", difficulty: "Hard", description: "Return the number of non-empty submatrices that sum to target.", testCases: [{ input: "[[0,1,0],[1,1,1],[0,1,0]]\\n0", output: "4", isHidden: false }], starterCode: "function numSubmatrixSumTarget(matrix, target) {\n    // Write your code here\n}" },

        // 2️⃣ TWO POINTERS (8 problems)
        { title: "Valid Palindrome", category: "Two Pointers", difficulty: "Easy", description: "Check if a string is a palindrome, considering only alphanumeric characters and ignoring cases.", testCases: [{ input: "\"A man, a plan, a canal: Panama\"", output: "true", isHidden: false }], starterCode: "function isPalindrome(s) {\n    // Write your code here\n}" },
        { title: "Remove Duplicates from Sorted Array", category: "Two Pointers", difficulty: "Easy", description: "Remove duplicates in-place from a sorted array and return the new length.", testCases: [{ input: "[1,1,2]", output: "2", isHidden: false }], starterCode: "function removeDuplicates(nums) {\n    // Write your code here\n}" },
        { title: "Merge Sorted Array", category: "Two Pointers", difficulty: "Easy", description: "Merge two sorted arrays nums1 and nums2 into nums1 as one sorted array.", testCases: [{ input: "[1,2,3,0,0,0]\\n3\\n[2,5,6]\\n3", output: "[1,2,2,3,5,6]", isHidden: false }], starterCode: "function merge(nums1, m, nums2, n) {\n    // Write your code here\n}" },
        { title: "3Sum", category: "Two Pointers", difficulty: "Medium", description: "Find all unique triplets in the array which gives the sum of zero.", testCases: [{ input: "[-1,0,1,2,-1,-4]", output: "[[-1,-1,2],[-1,0,1]]", isHidden: false }], starterCode: "function threeSum(nums) {\n    // Write your code here\n}" },
        { title: "Container With Most Water", category: "Two Pointers", difficulty: "Medium", description: "Find two lines that together with the x-axis form a container with the most water.", testCases: [{ input: "[1,8,6,2,5,4,8,3,7]", output: "49", isHidden: false }], starterCode: "function maxArea(height) {\n    // Write your code here\n}" },
        { title: "3Sum Closest", category: "Two Pointers", difficulty: "Medium", description: "Find three integers in nums such that the sum is closest to target.", testCases: [{ input: "[-1,2,1,-4]\\n1", output: "2", isHidden: false }], starterCode: "function threeSumClosest(nums, target) {\n    // Write your code here\n}" },
        { title: "4Sum", category: "Two Pointers", difficulty: "Medium", description: "Find all unique quadruplets in the array which gives the sum of target.", testCases: [{ input: "[1,0,-1,0,-2,2]\\n0", output: "[[-2,-1,1,2],[-2,0,0,2],[-1,0,0,1]]", isHidden: false }], starterCode: "function fourSum(nums, target) {\n    // Write your code here\n}" },
        { title: "Trapping Rain Water", category: "Two Pointers", difficulty: "Hard", description: "Compute how much water can be trapped after raining given elevation map.", testCases: [{ input: "[0,1,0,2,1,0,1,3,2,1,2,1]", output: "6", isHidden: false }], starterCode: "function trap(height) {\n    // Write your code here\n}" },

        // 3️⃣ SLIDING WINDOW (8 problems)
        { title: "Maximum Average Subarray I", category: "Sliding Window", difficulty: "Easy", description: "Find the contiguous subarray of length k that has the maximum average value.", testCases: [{ input: "[1,12,-5,-6,50,3]\\n4", output: "12.75", isHidden: false }], starterCode: "function findMaxAverage(nums, k) {\n    // Write your code here\n}" },
        { title: "Maximum Number of Vowels in a Substring", category: "Sliding Window", difficulty: "Easy", description: "Return the maximum number of vowel letters in any substring of s with length k.", testCases: [{ input: "\"abciiidef\"\\n3", output: "3", isHidden: false }], starterCode: "function maxVowels(s, k) {\n    // Write your code here\n}" },
        { title: "Longest Substring Without Repeating Characters", category: "Sliding Window", difficulty: "Medium", description: "Find the length of the longest substring without repeating characters.", testCases: [{ input: "\"abcabcbb\"", output: "3", isHidden: false }], starterCode: "function lengthOfLongestSubstring(s) {\n    // Write your code here\n}" },
        { title: "Max Consecutive Ones III", category: "Sliding Window", difficulty: "Medium", description: "Find the maximum number of consecutive 1's if you can flip at most k 0's.", testCases: [{ input: "[1,1,1,0,0,0,1,1,1,1,0]\\n2", output: "6", isHidden: false }], starterCode: "function longestOnes(nums, k) {\n    // Write your code here\n}" },
        { title: "Longest Repeating Character Replacement", category: "Sliding Window", difficulty: "Medium", description: "Find the length of the longest substring containing the same letter after k replacements.", testCases: [{ input: "\"ABAB\"\\n2", output: "4", isHidden: false }], starterCode: "function characterReplacement(s, k) {\n    // Write your code here\n}" },
        { title: "Permutation in String", category: "Sliding Window", difficulty: "Medium", description: "Check if one of s1's permutations is the substring of s2.", testCases: [{ input: "\"ab\"\\n\"eidbaooo\"", output: "true", isHidden: false }], starterCode: "function checkInclusion(s1, s2) {\n    // Write your code here\n}" },
        { title: "Find All Anagrams in a String", category: "Sliding Window", difficulty: "Medium", description: "Find all the start indices of p's anagrams in s.", testCases: [{ input: "\"cbaebabacd\"\\n\"abc\"", output: "[0,6]", isHidden: false }], starterCode: "function findAnagrams(s, p) {\n    // Write your code here\n}" },
        { title: "Minimum Window Substring", category: "Sliding Window", difficulty: "Hard", description: "Find the minimum window substring of s that contains all characters of t.", testCases: [{ input: "\"ADOBECODEBANC\"\\n\"ABC\"", output: "\"BANC\"", isHidden: false }], starterCode: "function minWindow(s, t) {\n    // Write your code here\n}" },

        // 4️⃣ FAST & SLOW POINTERS (5 problems)
        { title: "Linked List Cycle", category: "Fast & Slow Pointers", difficulty: "Easy", description: "Determine if a linked list has a cycle in it.", testCases: [{ input: "[3,2,0,-4]\\n1", output: "true", isHidden: false }], starterCode: "function hasCycle(head) {\n    // Write your code here\n}" },
        { title: "Middle of the Linked List", category: "Fast & Slow Pointers", difficulty: "Easy", description: "Return the middle node of the linked list.", testCases: [{ input: "[1,2,3,4,5]", output: "[3,4,5]", isHidden: false }], starterCode: "function middleNode(head) {\n    // Write your code here\n}" },
        { title: "Linked List Cycle II", category: "Fast & Slow Pointers", difficulty: "Medium", description: "Return the node where the cycle begins.", testCases: [{ input: "[3,2,0,-4]\\n1", output: "1", isHidden: false }], starterCode: "function detectCycle(head) {\n    // Write your code here\n}" },
        { title: "Find the Duplicate Number", category: "Fast & Slow Pointers", difficulty: "Medium", description: "Find the duplicate number in an array.", testCases: [{ input: "[1,3,4,2,2]", output: "2", isHidden: false }], starterCode: "function findDuplicate(nums) {\n    // Write your code here\n}" },
        { title: "Happy Number", category: "Fast & Slow Pointers", difficulty: "Medium", description: "Determine if a number n is happy.", testCases: [{ input: "19", output: "true", isHidden: false }], starterCode: "function isHappy(n) {\n    // Write your code here\n}" },

        // 5️⃣ LINKED LIST IN-PLACE REVERSAL (6 problems)
        { title: "Reverse Linked List", category: "Linked List In-Place Reversal", difficulty: "Easy", description: "Reverse a singly linked list.", testCases: [{ input: "[1,2,3,4,5]", output: "[5,4,3,2,1]", isHidden: false }], starterCode: "function reverseList(head) {\n    // Write your code here\n}" },
        { title: "Reverse Linked List II", category: "Linked List In-Place Reversal", difficulty: "Medium", description: "Reverse a linked list from position left to right.", testCases: [{ input: "[1,2,3,4,5]\\n2\\n4", output: "[1,4,3,2,5]", isHidden: false }], starterCode: "function reverseBetween(head, left, right) {\n    // Write your code here\n}" },
        { title: "Swap Nodes in Pairs", category: "Linked List In-Place Reversal", difficulty: "Medium", description: "Swap every two adjacent nodes and return its head.", testCases: [{ input: "[1,2,3,4]", output: "[2,1,4,3]", isHidden: false }], starterCode: "function swapPairs(head) {\n    // Write your code here\n}" },
        { title: "Remove Nth Node From End", category: "Linked List In-Place Reversal", difficulty: "Medium", description: "Remove the nth node from the end of the list.", testCases: [{ input: "[1,2,3,4,5]\\n2", output: "[1,2,3,5]", isHidden: false }], starterCode: "function removeNthFromEnd(head, n) {\n    // Write your code here\n}" },
        { title: "Reorder List", category: "Linked List In-Place Reversal", difficulty: "Medium", description: "Reorder the list: L0 → Ln → L1 → Ln-1 → …", testCases: [{ input: "[1,2,3,4]", output: "[1,4,2,3]", isHidden: false }], starterCode: "function reorderList(head) {\n    // Write your code here\n}" },
        { title: "Reverse Nodes in k-Group", category: "Linked List In-Place Reversal", difficulty: "Hard", description: "Reverse the nodes of the list k at a time.", testCases: [{ input: "[1,2,3,4,5]\\n2", output: "[2,1,4,3,5]", isHidden: false }], starterCode: "function reverseKGroup(head, k) {\n    // Write your code here\n}" },

        // 6️⃣ MONOTONIC STACK (6 problems)
        { title: "Next Greater Element I", category: "Monotonic Stack", difficulty: "Easy", description: "Find the next greater number for every element in nums1 from nums2.", testCases: [{ input: "[4,1,2]\\n[1,3,4,2]", output: "[-1,3,-1]", isHidden: false }], starterCode: "function nextGreaterElement(nums1, nums2) {\n    // Write your code here\n}" },
        { title: "Daily Temperatures", category: "Monotonic Stack", difficulty: "Medium", description: "Return an array where each element is the number of days to wait for a warmer temperature.", testCases: [{ input: "[73,74,75,71,69,72,76,73]", output: "[1,1,4,2,1,1,0,0]", isHidden: false }], starterCode: "function dailyTemperatures(temperatures) {\n    // Write your code here\n}" },
        { title: "Next Greater Element II", category: "Monotonic Stack", difficulty: "Medium", description: "Find the next greater number for every element in a circular array.", testCases: [{ input: "[1,2,1]", output: "[2,-1,2]", isHidden: false }], starterCode: "function nextGreaterElements(nums) {\n    // Write your code here\n}" },
        { title: "Online Stock Span", category: "Monotonic Stack", difficulty: "Medium", description: "Calculate the span of stock's price for the current day.", testCases: [{ input: "[100,80,60,70,60,75,85]", output: "[1,1,1,2,1,4,6]", isHidden: false }], starterCode: "class StockSpanner {\n    constructor() {}\n    next(price) {}\n}" },
        { title: "Largest Rectangle in Histogram", category: "Monotonic Stack", difficulty: "Hard", description: "Find the largest rectangle in a histogram.", testCases: [{ input: "[2,1,5,6,2,3]", output: "10", isHidden: false }], starterCode: "function largestRectangleArea(heights) {\n    // Write your code here\n}" },
        { title: "Trapping Rain Water (Stack)", category: "Monotonic Stack", difficulty: "Hard", description: "Compute how much water can be trapped after raining (monotonic stack approach).", testCases: [{ input: "[0,1,0,2,1,0,1,3,2,1,2,1]", output: "6", isHidden: false }], starterCode: "function trap(height) {\n    // Write your code here\n}" },

        // 7️⃣ TOP K ELEMENTS (5 problems)
        { title: "Kth Largest Element in a Stream", category: "Top K Elements", difficulty: "Easy", description: "Design a class to find the kth largest element in a stream.", testCases: [{ input: "3\\n[4,5,8,2]\\n3", output: "4", isHidden: false }], starterCode: "class KthLargest {\n    constructor(k, nums) {}\n    add(val) {}\n}" },
        { title: "Kth Largest Element in an Array", category: "Top K Elements", difficulty: "Medium", description: "Find the kth largest element in an unsorted array.", testCases: [{ input: "[3,2,1,5,6,4]\\n2", output: "5", isHidden: false }], starterCode: "function findKthLargest(nums, k) {\n    // Write your code here\n}" },
        { title: "Top K Frequent Elements", category: "Top K Elements", difficulty: "Medium", description: "Return the k most frequent elements.", testCases: [{ input: "[1,1,1,2,2,3]\\n2", output: "[1,2]", isHidden: false }], starterCode: "function topKFrequent(nums, k) {\n    // Write your code here\n}" },
        { title: "K Closest Points to Origin", category: "Top K Elements", difficulty: "Medium", description: "Find the k closest points to the origin (0, 0).", testCases: [{ input: "[[1,3],[-2,2]]\\n1", output: "[[-2,2]]", isHidden: false }], starterCode: "function kClosest(points, k) {\n    // Write your code here\n}" },
        { title: "Find Median from Data Stream", category: "Top K Elements", difficulty: "Hard", description: "Design a data structure that supports adding integers and finding the median.", testCases: [{ input: "[1,2]", output: "1.5", isHidden: false }], starterCode: "class MedianFinder {\n    constructor() {}\n    addNum(num) {}\n    findMedian() {}\n}" },

        // 8️⃣ OVERLAPPING INTERVALS (6 problems)
        { title: "Meeting Rooms", category: "Overlapping Intervals", difficulty: "Easy", description: "Determine if a person could attend all meetings.", testCases: [{ input: "[[0,30],[5,10],[15,20]]", output: "false", isHidden: false }], starterCode: "function canAttendMeetings(intervals) {\n    // Write your code here\n}" },
        { title: "Merge Intervals", category: "Overlapping Intervals", difficulty: "Medium", description: "Merge all overlapping intervals.", testCases: [{ input: "[[1,3],[2,6],[8,10],[15,18]]", output: "[[1,6],[8,10],[15,18]]", isHidden: false }], starterCode: "function merge(intervals) {\n    // Write your code here\n}" },
        { title: "Insert Interval", category: "Overlapping Intervals", difficulty: "Medium", description: "Insert a new interval into a sorted list of non-overlapping intervals and merge if necessary.", testCases: [{ input: "[[1,3],[6,9]]\\n[2,5]", output: "[[1,5],[6,9]]", isHidden: false }], starterCode: "function insert(intervals, newInterval) {\n    // Write your code here\n}" },
        { title: "Non-Overlapping Intervals", category: "Overlapping Intervals", difficulty: "Medium", description: "Find the minimum number of intervals to remove to make the rest non-overlapping.", testCases: [{ input: "[[1,2],[2,3],[3,4],[1,3]]", output: "1", isHidden: false }], starterCode: "function eraseOverlapIntervals(intervals) {\n    // Write your code here\n}" },
        { title: "Interval List Intersections", category: "Overlapping Intervals", difficulty: "Medium", description: "Find the intersection of two interval lists.", testCases: [{ input: "[[0,2],[5,10]]\\n[[1,5],[8,12]]", output: "[[1,2],[5,5],[8,10]]", isHidden: false }], starterCode: "function intervalIntersection(firstList, secondList) {\n    // Write your code here\n}" },
        { title: "The Skyline Problem", category: "Overlapping Intervals", difficulty: "Hard", description: "Return the skyline formed by buildings.", testCases: [{ input: "[[2,9,10],[3,7,15],[5,12,12]]", output: "[[2,10],[3,15],[7,12],[12,0]]", isHidden: false }], starterCode: "function getSkyline(buildings) {\n    // Write your code here\n}" },

        // 9️⃣ MODIFIED BINARY SEARCH (7 problems)
        { title: "Binary Search", category: "Modified Binary Search", difficulty: "Easy", description: "Search for a target value in a sorted array.", testCases: [{ input: "[-1,0,3,5,9,12]\\n9", output: "4", isHidden: false }], starterCode: "function search(nums, target) {\n    // Write your code here\n}" },
        { title: "Search Insert Position", category: "Modified Binary Search", difficulty: "Easy", description: "Find the index if the target is found, or where it would be inserted.", testCases: [{ input: "[1,3,5,6]\\n5", output: "2", isHidden: false }], starterCode: "function searchInsert(nums, target) {\n    // Write your code here\n}" },
        { title: "Search in Rotated Sorted Array", category: "Modified Binary Search", difficulty: "Medium", description: "Search for a target value in a rotated sorted array.", testCases: [{ input: "[4,5,6,7,0,1,2]\\n0", output: "4", isHidden: false }], starterCode: "function search(nums, target) {\n    // Write your code here\n}" },
        { title: "Find Minimum in Rotated Sorted Array", category: "Modified Binary Search", difficulty: "Medium", description: "Find the minimum element in a rotated sorted array.", testCases: [{ input: "[3,4,5,1,2]", output: "1", isHidden: false }], starterCode: "function findMin(nums) {\n    // Write your code here\n}" },
        { title: "Find Peak Element", category: "Modified Binary Search", difficulty: "Medium", description: "Find a peak element and return its index.", testCases: [{ input: "[1,2,3,1]", output: "2", isHidden: false }], starterCode: "function findPeakElement(nums) {\n    // Write your code here\n}" },
        { title: "Find First and Last Position", category: "Modified Binary Search", difficulty: "Medium", description: "Find the starting and ending position of a target in a sorted array.", testCases: [{ input: "[5,7,7,8,8,10]\\n8", output: "[3,4]", isHidden: false }], starterCode: "function searchRange(nums, target) {\n    // Write your code here\n}" },
        { title: "Median of Two Sorted Arrays", category: "Modified Binary Search", difficulty: "Hard", description: "Find the median of two sorted arrays.", testCases: [{ input: "[1,3]\\n[2]", output: "2.00000", isHidden: false }], starterCode: "function findMedianSortedArrays(nums1, nums2) {\n    // Write your code here\n}" },

        // 🔟 BINARY TREE TRAVERSAL (7 problems)
        { title: "Inorder Traversal", category: "Binary Tree Traversal", difficulty: "Easy", description: "Return the inorder traversal of a binary tree's nodes' values.", testCases: [{ input: "[1,null,2,3]", output: "[1,3,2]", isHidden: false }], starterCode: "function inorderTraversal(root) {\n    // Write your code here\n}" },
        { title: "Preorder Traversal", category: "Binary Tree Traversal", difficulty: "Easy", description: "Return the preorder traversal of a binary tree's nodes' values.", testCases: [{ input: "[1,null,2,3]", output: "[1,2,3]", isHidden: false }], starterCode: "function preorderTraversal(root) {\n    // Write your code here\n}" },
        { title: "Postorder Traversal", category: "Binary Tree Traversal", difficulty: "Easy", description: "Return the postorder traversal of a binary tree's nodes' values.", testCases: [{ input: "[1,null,2,3]", output: "[3,2,1]", isHidden: false }], starterCode: "function postorderTraversal(root) {\n    // Write your code here\n}" },
        { title: "Validate BST", category: "Binary Tree Traversal", difficulty: "Medium", description: "Determine if a binary tree is a valid binary search tree.", testCases: [{ input: "[2,1,3]", output: "true", isHidden: false }], starterCode: "function isValidBST(root) {\n    // Write your code here\n}" },
        { title: "Kth Smallest in BST", category: "Binary Tree Traversal", difficulty: "Medium", description: "Find the kth smallest element in a BST.", testCases: [{ input: "[3,1,4,null,2]\\n1", output: "1", isHidden: false }], starterCode: "function kthSmallest(root, k) {\n    // Write your code here\n}" },
        { title: "Lowest Common Ancestor", category: "Binary Tree Traversal", difficulty: "Medium", description: "Find the lowest common ancestor of two nodes in a BST.", testCases: [{ input: "[6,2,8,0,4,7,9]\\n2\\n8", output: "6", isHidden: false }], starterCode: "function lowestCommonAncestor(root, p, q) {\n    // Write your code here\n}" },
        { title: "Binary Tree Maximum Path Sum", category: "Binary Tree Traversal", difficulty: "Hard", description: "Find the maximum path sum in a binary tree.", testCases: [{ input: "[1,2,3]", output: "6", isHidden: false }], starterCode: "function maxPathSum(root) {\n    // Write your code here\n}" },

        // 1️⃣1️⃣ DFS (4 problems)
        { title: "Number of Islands", category: "DFS", difficulty: "Medium", description: "Count the number of islands in a 2D grid.", testCases: [{ input: "[[\"1\",\"1\",\"0\"],[\"0\",\"0\",\"1\"]]", output: "2", isHidden: false }], starterCode: "function numIslands(grid) {\n    // Write your code here\n}" },
        { title: "Clone Graph", category: "DFS", difficulty: "Medium", description: "Return a deep copy of an undirected graph.", testCases: [{ input: "[[2,4],[1,3],[2,4],[1,3]]", output: "[[2,4],[1,3],[2,4],[1,3]]", isHidden: false }], starterCode: "function cloneGraph(node) {\n    // Write your code here\n}" },
        { title: "All Paths From Source to Target", category: "DFS", difficulty: "Medium", description: "Find all possible paths from node 0 to node n-1 in a directed acyclic graph.", testCases: [{ input: "[[1,2],[3],[3],[]]", output: "[[0,1,3],[0,2,3]]", isHidden: false }], starterCode: "function allPathsSourceTarget(graph) {\n    // Write your code here\n}" },
        { title: "Longest Increasing Path in a Matrix", category: "DFS", difficulty: "Hard", description: "Find the length of the longest increasing path in a matrix.", testCases: [{ input: "[[9,9,4],[6,6,8],[2,1,1]]", output: "4", isHidden: false }], starterCode: "function longestIncreasingPath(matrix) {\n    // Write your code here\n}" },

        // 1️⃣2️⃣ BFS (5 problems)
        { title: "Level Order Traversal", category: "BFS", difficulty: "Medium", description: "Return the level order traversal of a binary tree's nodes' values.", testCases: [{ input: "[3,9,20,null,null,15,7]", output: "[[3],[9,20],[15,7]]", isHidden: false }], starterCode: "function levelOrder(root) {\n    // Write your code here\n}" },
        { title: "Rotting Oranges", category: "BFS", difficulty: "Medium", description: "Find the minimum number of minutes until no cell has a fresh orange.", testCases: [{ input: "[[2,1,1],[1,1,0],[0,1,1]]", output: "4", isHidden: false }], starterCode: "function orangesRotting(grid) {\n    // Write your code here\n}" },
        { title: "Word Ladder", category: "BFS", difficulty: "Medium", description: "Find the length of the shortest transformation sequence from beginWord to endWord.", testCases: [{ input: "\"hit\"\\n\"cog\"\\n[\"hot\",\"dot\",\"dog\",\"lot\",\"log\",\"cog\"]", output: "5", isHidden: false }], starterCode: "function ladderLength(beginWord, endWord, wordList) {\n    // Write your code here\n}" },
        { title: "Open the Lock", category: "BFS", difficulty: "Medium", description: "Find the minimum total number of turns required to open the lock.", testCases: [{ input: "[\"0201\",\"0101\",\"0102\",\"1212\",\"2002\"]\\n\"0202\"", output: "6", isHidden: false }], starterCode: "function openLock(deadends, target) {\n    // Write your code here\n}" },
        { title: "Bus Routes", category: "BFS", difficulty: "Hard", description: "Find the least number of buses to travel from source to target.", testCases: [{ input: "[[1,2,7],[3,6,7]]\\n1\\n6", output: "2", isHidden: false }], starterCode: "function numBusesToDestination(routes, source, target) {\n    // Write your code here\n}" },

        // 1️⃣3️⃣ MATRIX TRAVERSAL (5 problems)
        { title: "Flood Fill", category: "Matrix Traversal", difficulty: "Easy", description: "Perform a flood fill on an image starting from pixel (sr, sc).", testCases: [{ input: "[[1,1,1],[1,1,0],[1,0,1]]\\n1\\n1\\n2", output: "[[2,2,2],[2,2,0],[2,0,1]]", isHidden: false }], starterCode: "function floodFill(image, sr, sc, color) {\n    // Write your code here\n}" },
        { title: "Surrounded Regions", category: "Matrix Traversal", difficulty: "Medium", description: "Capture all regions that are surrounded by 'X'.", testCases: [{ input: "[[\"X\",\"X\"],[\"X\",\"O\"]]", output: "[[\"X\",\"X\"],[\"X\",\"O\"]]", isHidden: false }], starterCode: "function solve(board) {\n    // Write your code here\n}" },
        { title: "Spiral Matrix", category: "Matrix Traversal", difficulty: "Medium", description: "Return all elements of the matrix in spiral order.", testCases: [{ input: "[[1,2,3],[4,5,6],[7,8,9]]", output: "[1,2,3,6,9,8,7,4,5]", isHidden: false }], starterCode: "function spiralOrder(matrix) {\n    // Write your code here\n}" },
        { title: "Rotate Image", category: "Matrix Traversal", difficulty: "Medium", description: "Rotate the image by 90 degrees clockwise in-place.", testCases: [{ input: "[[1,2,3],[4,5,6],[7,8,9]]", output: "[[7,4,1],[8,5,2],[9,6,3]]", isHidden: false }], starterCode: "function rotate(matrix) {\n    // Write your code here\n}" },
        { title: "Maximal Rectangle", category: "Matrix Traversal", difficulty: "Hard", description: "Find the largest rectangle containing only 1's in a binary matrix.", testCases: [{ input: "[[\"1\",\"0\",\"1\"],[\"1\",\"1\",\"1\"]]", output: "3", isHidden: false }], starterCode: "function maximalRectangle(matrix) {\n    // Write your code here\n}" },

        // 1️⃣4️⃣ BACKTRACKING (6 problems)
        { title: "Subsets", category: "Backtracking", difficulty: "Easy", description: "Return all possible subsets (the power set).", testCases: [{ input: "[1,2,3]", output: "[[],[1],[2],[1,2],[3],[1,3],[2,3],[1,2,3]]", isHidden: false }], starterCode: "function subsets(nums) {\n    // Write your code here\n}" },
        { title: "Permutations", category: "Backtracking", difficulty: "Medium", description: "Return all possible permutations.", testCases: [{ input: "[1,2,3]", output: "[[1,2,3],[1,3,2],[2,1,3],[2,3,1],[3,1,2],[3,2,1]]", isHidden: false }], starterCode: "function permute(nums) {\n    // Write your code here\n}" },
        { title: "Combination Sum", category: "Backtracking", difficulty: "Medium", description: "Find all unique combinations where the candidate numbers sum to target.", testCases: [{ input: "[2,3,6,7]\\n7", output: "[[2,2,3],[7]]", isHidden: false }], starterCode: "function combinationSum(candidates, target) {\n    // Write your code here\n}" },
        { title: "Letter Combinations of a Phone Number", category: "Backtracking", difficulty: "Medium", description: "Return all possible letter combinations that the number could represent.", testCases: [{ input: "\"23\"", output: "[\"ad\",\"ae\",\"af\",\"bd\",\"be\",\"bf\",\"cd\",\"ce\",\"cf\"]", isHidden: false }], starterCode: "function letterCombinations(digits) {\n    // Write your code here\n}" },
        { title: "N-Queens", category: "Backtracking", difficulty: "Hard", description: "Solve the n-queens puzzle.", testCases: [{ input: "4", output: "[\".Q..\",\"...Q\",\"Q...\",\"..Q.\"]", isHidden: false }], starterCode: "function solveNQueens(n) {\n    // Write your code here\n}" },
        { title: "Sudoku Solver", category: "Backtracking", difficulty: "Hard", description: "Solve a Sudoku puzzle by filling the empty cells.", testCases: [{ input: "partial board", output: "solved board", isHidden: false }], starterCode: "function solveSudoku(board) {\n    // Write your code here\n}" },

        // 1️⃣5️⃣ DYNAMIC PROGRAMMING (9 problems)
        { title: "Climbing Stairs", category: "Dynamic Programming", difficulty: "Easy", description: "Find the number of distinct ways you can climb to the top.", testCases: [{ input: "2", output: "2", isHidden: false }], starterCode: "function climbStairs(n) {\n    // Write your code here\n}" },
        { title: "Min Cost Climbing Stairs", category: "Dynamic Programming", difficulty: "Easy", description: "Find the minimum cost to reach the top of the floor.", testCases: [{ input: "[10,15,20]", output: "15", isHidden: false }], starterCode: "function minCostClimbingStairs(cost) {\n    // Write your code here\n}" },
        { title: "House Robber", category: "Dynamic Programming", difficulty: "Medium", description: "Determine the maximum amount of money you can rob without alerting the police.", testCases: [{ input: "[1,2,3,1]", output: "4", isHidden: false }], starterCode: "function rob(nums) {\n    // Write your code here\n}" },
        { title: "Coin Change", category: "Dynamic Programming", difficulty: "Medium", description: "Find the fewest number of coins needed to make up that amount.", testCases: [{ input: "[1,2,5]\\n11", output: "3", isHidden: false }], starterCode: "function coinChange(coins, amount) {\n    // Write your code here\n}" },
        { title: "Longest Increasing Subsequence", category: "Dynamic Programming", difficulty: "Medium", description: "Find the length of the longest strictly increasing subsequence.", testCases: [{ input: "[10,9,2,5,3,7,101,18]", output: "4", isHidden: false }], starterCode: "function lengthOfLIS(nums) {\n    // Write your code here\n}" },
        { title: "Longest Common Subsequence", category: "Dynamic Programming", difficulty: "Medium", description: "Find the length of the longest common subsequence of two strings.", testCases: [{ input: "\"abcde\"\\n\"ace\"", output: "3", isHidden: false }], starterCode: "function longestCommonSubsequence(text1, text2) {\n    // Write your code here\n}" },
        { title: "Partition Equal Subset Sum", category: "Dynamic Programming", difficulty: "Medium", description: "Determine if the array can be partitioned into two subsets with equal sum.", testCases: [{ input: "[1,5,11,5]", output: "true", isHidden: false }], starterCode: "function canPartition(nums) {\n    // Write your code here\n}" },
        { title: "Edit Distance", category: "Dynamic Programming", difficulty: "Hard", description: "Find the minimum number of operations required to convert word1 to word2.", testCases: [{ input: "\"horse\"\\n\"ros\"", output: "3", isHidden: false }], starterCode: "function minDistance(word1, word2) {\n    // Write your code here\n}" },
        { title: "Burst Balloons", category: "Dynamic Programming", difficulty: "Hard", description: "Find the maximum coins you can collect by bursting the balloons wisely.", testCases: [{ input: "[3,1,5,8]", output: "167", isHidden: false }], starterCode: "function maxCoins(nums) {\n    // Write your code here\n}" },
    ];

    try {
        await Problem.deleteMany({});
        await Problem.insertMany(problems);
        const breakdown = problems.reduce((acc, p) => {
            acc[p.category] = (acc[p.category] || 0) + 1;
            return acc;
        }, {});
        res.json({
            success: true,
            message: `✅ Successfully seeded ${problems.length} problems!`,
            breakdown
        });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

export default router;
